### ISSUE TITLE
Error on trying to init the project from the example

### ISSUE THREAD

**Issue by stuk88** [sunriselink/TelegramApi#3]
This is what i get in the console:
`telegramApi.js:1172 Pq leemon Exception ReferenceError: str2bigInt is not defined(…)pqPrimeFactorization @ telegramApi.js:1172(anonymous function) @ telegramApi.js:575(anonymous function) @ telegramApi.js:146handleMessage @ telegramApi.js:1729
telegramApi.js:1180 Pq long Exception ReferenceError: goog is not defined(…)pqPrimeFactorization @ telegramApi.js:1180(anonymous function) @ telegramApi.js:575(anonymous function) @ telegramApi.js:146handleMessage @ telegramApi.js:1729
telegramApi.js:2989 [4.201] PQ factorization done 51447
telegramApi.js:3034 [4.206] Send req_DH_params
telegramApi.js:3103 [4.733] Done decrypting answer
telegramApi.js:4533 [4.734] Apply server time 1480535465 1480535465012 0 false
telegramApi.js:1413 mod pow error ReferenceError: str2bigInt is not defined(…)bytesModPow @ telegramApi.js:1413(anonymous function) @ telegramApi.js:580(anonymous function) @ telegramApi.js:146handleMessage @ telegramApi.js:1729
telegramApi.js:3147 [4.869] Send set_client_DH_params
telegramApi.js:1413 mod pow error ReferenceError: str2bigInt is not defined(…)bytesModPow @ telegramApi.js:1413(anonymous function) @ telegramApi.js:580(anonymous function) @ telegramApi.js:146handleMessage @ telegramApi.js:1729
telegramApi.js:3171 [5.334] Got Set_client_DH_params_answer dh_gen_ok
telegramApi.js:3478 [5.337] Api call help.getNearestDc
telegramApi.js:4257 [5.638] Rpc response nearestDc
telegramApi.js:2723 Get networker error Error: No server found for dc 4(…) Error: No server found for dc 4
    at Object.mtpAuth [as auth] (file:///Users/stasarshanski/Documents/telegram_test/js/telegramApi.js:3234:30)
    at Object.<anonymous> (file:///Users/stasarshanski/Documents/telegram_test/js/telegramApi.js:2715:34)
    at Object.<anonymous> (https://code.jquery.com/jquery-2.2.4.min.js:2:28469)
    at i (https://code.jquery.com/jquery-2.2.4.min.js:2:27151)
    at Object.add [as done] (https://code.jquery.com/jquery-2.2.4.min.js:2:27450)
    at Array.<anonymous> (https://code.jquery.com/jquery-2.2.4.min.js:2:28446)
    at Function.each (https://code.jquery.com/jquery-2.2.4.min.js:2:2861)
    at Object.<anonymous> (https://code.jquery.com/jquery-2.2.4.min.js:2:28387)
    at Function.Deferred (https://code.jquery.com/jquery-2.2.4.min.js:2:28973)
    at Object.then (https://code.jquery.com/jquery-2.2.4.min.js:2:28364)
telegramApi.js:3478 [19.305] Api call auth.sendCode
telegramApi.js:4240 [19.955] Rpc error Object {code: 303, type: "PHONE_MIGRATE_4", description: "CODE#303 PHONE_MIGRATE_4", originalError: Object}
telegramApi.js:2772 [19.956] Error 303 PHONE_MIGRATE_4 false 2(anonymous function) @ telegramApi.js:2772(anonymous function) @ jquery-2.2.4.min.js:2i @ jquery-2.2.4.min.js:2fireWith @ jquery-2.2.4.min.js:2e.(anonymous function) @ jquery-2.2.4.min.js:2MtpNetworkerFactoryModule.MtpNetworker.processMessage @ telegramApi.js:4242(anonymous function) @ telegramApi.js:3810(anonymous function) @ jquery-2.2.4.min.js:2i @ jquery-2.2.4.min.js:2fireWith @ jquery-2.2.4.min.js:2e.(anonymous function) @ jquery-2.2.4.min.js:2i @ jquery-2.2.4.min.js:2fireWith @ jquery-2.2.4.min.js:2(anonymous function) @ jquery-2.2.4.min.js:2i @ jquery-2.2.4.min.js:2fireWith @ jquery-2.2.4.min.js:2e.(anonymous function) @ jquery-2.2.4.min.js:2(anonymous function) @ telegramApi.js:146handleMessage @ telegramApi.js:1729
telegramApi.js:2723 Get networker error Error: No server found for dc 4(…) Error: No server found for dc 4
    at Object.mtpAuth [as auth] (file:///Users/stasarshanski/Documents/telegram_test/js/telegramApi.js:3234:30)
    at Object.<anonymous> (file:///Users/stasarshanski/Documents/telegram_test/js/telegramApi.js:2715:34)
    at Object.<anonymous> (https://code.jquery.com/jquery-2.2.4.min.js:2:28469)
    at i (https://code.jquery.com/jquery-2.2.4.min.js:2:27151)
    at Object.add [as done] (https://code.jquery.com/jquery-2.2.4.min.js:2:27450)
    at Array.<anonymous> (https://code.jquery.com/jquery-2.2.4.min.js:2:28446)
    at Function.each (https://code.jquery.com/jquery-2.2.4.min.js:2:2861)
    at Object.<anonymous> (https://code.jquery.com/jquery-2.2.4.min.js:2:28387)
    at Function.Deferred (https://code.jquery.com/jquery-2.2.4.min.js:2:28973)
    at Object.then (https://code.jquery.com/jquery-2.2.4.min.js:2:28364)
script.js:54 Object {promise: Object, input: "auth.sendCode", stack: "Error↵    at Object.rejectPromise (file:///Users/s…ocuments/telegram_test/js/telegramApi.js:2813:63)", $$hashKey: "object:44", handled: true}$$hashKey: "object:44"always: ()done: ()fail: ()handled: trueinput: "auth.sendCode"notify: ()notifyWith: (a,c)pipe: ()progress: ()promise: Objectreject: ()rejectWith: (a,c)resolve: ()resolveWith: (a,c)stack: "Error↵    at Object.rejectPromise (file:///Users/stasarshanski/Documents/telegram_test/js/telegramApi.js:2743:103)↵    at Object.<anonymous> (https://code.jquery.com/jquery-2.2.4.min.js:2:28469)↵    at i (https://code.jquery.com/jquery-2.2.4.min.js:2:27151)↵    at Object.add [as fail] (https://code.jquery.com/jquery-2.2.4.min.js:2:27450)↵    at Array.<anonymous> (https://code.jquery.com/jquery-2.2.4.min.js:2:28446)↵    at Function.each (https://code.jquery.com/jquery-2.2.4.min.js:2:2861)↵    at Object.<anonymous> (https://code.jquery.com/jquery-2.2.4.min.js:2:28387)↵    at Function.Deferred (https://code.jquery.com/jquery-2.2.4.min.js:2:28973)↵    at Object.then (https://code.jquery.com/jquery-2.2.4.min.js:2:28364)↵    at Object.<anonymous> (file:///Users/stasarshanski/Documents/telegram_test/js/telegramApi.js:2813:63)"state: ()then: ()__proto__: Object
script.js:54 Object {promise: Object, input: "auth.sendCode", stack: "Error↵    at Object.rejectPromise (file:///Users/s…ocuments/telegram_test/js/telegramApi.js:2813:63)", $$hashKey: "object:44", handled: true}`

**Comment by sunriselink** [comment]
Hi, I suggested a possible solution to this problem
https://github.com/sunriselink/TelegramApi/issues/2#issuecomment-264126220
